<a href="https://colab.research.google.com/github/clobos/Biologia_2026/blob/main/Semana01_Biologia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pergunta 1: O que é Estatística?

# Pergunta 2: Para que serve a Estatística?

# Tipos de variáveis

## Qual. nominal
- Exemplo 1
- Exemplo 2
- Exemplo 3

## Qual. ordinal
- Exemplo 1
- Exemplo 2
- Exemplo 3

## Quant. discreta
- Exemplo 1
- Exemplo 2
- Exemplo 3

## Quant. continua
- Exemplo 1
- Exemplo 2
- Exemplo 3

In [21]:
import pandas as pd
df = pd.read_excel('dados_semana1.xlsx')
df

,Quantos cafés você consumiu nas últimas 24 horas?,"Qual é a temperatura ideal, em °C, para beber café filtrado?",Qual dessas frutas você prefere para suco natural?,Como você classificaria o nível de doçura ideal de um iogurte?,"Quantas refeições você faz por dia, em média?","Qual foi o peso, em gramas, da última porção de arroz que você consumiu?",Qual tipo de dieta você segue atualmente?,Como você avalia sua preferência por alimentos crocantes?,"Quanto tempo, em minutos, você normalmente leva para preparar o café da manhã?"
0,0,0,Manga,Baixo,2,200,Onívora,3,0
1,0,70,Maracujá,Médio,4,100g,Outra,3,30
2,0,40,Laranja,Médio,4,100,Onívora,4,10 minutos
3,0,50,Laranja,Baixo,3,100,Onívora,5,20
4,6 xicaras,30°C?,Melancia,Médio,5,70g,Onívora,5,30 minutos
5,1,55,Morango,Baixo,4,200,Vegetariana,5,30min
6,2,15,Laranja,Alto,2,100,Onívora,5,0
7,0,62,cupuaçu,Médio,3,150,Onívora,3,5
8,4 canecas,uns 50-60 sei nao,Maracujá,Muito baixo,5,umas 100g,Onívora,5,uns 15
9,1,55°C,Laranja,Médio,6,70g,Onívora,4,15min
10,3 xícaras,30°C,Laranja,Médio,duas e meia/ três,Não sei dizer,Onívora,4,20 min
11,0,90,Maçã,Médio,Duas,100g,Onívora,5,0
12,2,55,Laranja,Baixo,3,70,Onívora,5,15 minutos
13,Nenhum,92C,Abacaxi,Baixo,Três refeições,Não consumo arroz,Onívora,1,Cerca de 12 minutos
14,7,27°C,Laranja,Médio,3,120g,Onívora,5,25 minutos
15,3,75⁰c,Laranja,Baixo,3,250,Onívora,4,15min
16,1,60ºC,Maracujá,Médio,5,50g,Onívora,1,30 min
17,1 xícara de 300ml,39°C,Maracujá,Médio,2 refeições,150g,Onívora,5,"Não tomo café da manhã, e a moça que trabalha ..."
18,1,75°C,Maracujá,Médio,2,300,Onívora,5,5 minutos
19,0,50º,Laranja,Médio,4,250,Onívora,4,10
20,2,50,Laranja,Médio,3,300,Onívora,4,2
21,0,35,Laranja,Médio,3,50,Onívora,4,10
22,nenhum,65,Maracujá,Baixo,3,80g,Onívora,1,20 minutos
23,1,65,Laranja,Médio,3,200,Onívora,5,5

In [3]:
linhas, colunas = df.shape
print(f"Número de linhas: {linhas}")
print(f"Número de colunas: {colunas}\n")

Número de linhas: 24
Número de colunas: 9

In [22]:
print("Tipos de variáveis (dtypes):")
print(df.dtypes)

Tipos de variáveis (dtypes):
Quantos cafés você consumiu nas últimas 24 horas?                                 object
Qual é a temperatura ideal, em °C, para beber café filtrado?                      object
Qual dessas frutas você prefere para suco natural?                                object
Como você classificaria o nível de doçura ideal de um iogurte?                    object
Quantas refeições você faz por dia, em média?                                     object
Qual foi o peso, em gramas, da última porção de arroz que você consumiu?          object
Qual tipo de dieta você segue atualmente?                                         object
Como você avalia sua preferência por alimentos crocantes?                          int64
Quanto tempo, em minutos, você normalmente leva para preparar o café da manhã?    object
dtype: object

In [15]:
# Informações detalhadas do DataFrame
print("Informações gerais do banco:")
df.info()

Informações gerais do banco:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 9 columns):
 #   Column                                                                          Non-Null Count  Dtype
---  ------                                                                          --------------  -----
 0   Quantos cafés você consumiu nas últimas 24 horas?                               24 non-null     object
 1   Qual é a temperatura ideal, em °C, para beber café filtrado?                    24 non-null     object
 2   Qual dessas frutas você prefere para suco natural?                              24 non-null     object
 3   Como você classificaria o nível de doçura ideal de um iogurte?                  24 non-null     object
 4   Quantas refeições você faz por dia, em média?                                   24 non-null     object
 5   Qual foi o peso, em gramas, da última porção de arroz que você consumiu?        24 non-null     object
 6   Qual tipo de dieta você segue atualmente?                                       24 non-null     object
 7   Como você avalia sua preferência por alimentos crocantes?                       24 non-null     int64
 8   Quanto tempo, em minutos, você normalmente leva para preparar o café da manhã?  24 non-null     object
dtypes: int64(1), object(8)
memory usage: 1.8+ KB

In [23]:
print("5 primeiras linhas:")
display(df.head())

5 primeiras linhas:

,Quantos cafés você consumiu nas últimas 24 horas?,"Qual é a temperatura ideal, em °C, para beber café filtrado?",Qual dessas frutas você prefere para suco natural?,Como você classificaria o nível de doçura ideal de um iogurte?,"Quantas refeições você faz por dia, em média?","Qual foi o peso, em gramas, da última porção de arroz que você consumiu?",Qual tipo de dieta você segue atualmente?,Como você avalia sua preferência por alimentos crocantes?,"Quanto tempo, em minutos, você normalmente leva para preparar o café da manhã?"
0,0,0,Manga,Baixo,2,200,Onívora,3,0
1,0,70,Maracujá,Médio,4,100g,Outra,3,30
2,0,40,Laranja,Médio,4,100,Onívora,4,10 minutos
3,0,50,Laranja,Baixo,3,100,Onívora,5,20
4,6 xicaras,30°C?,Melancia,Médio,5,70g,Onívora,5,30 minutos

In [24]:
print("5 últimas linhas:")
display(df.tail())

5 últimas linhas:

,Quantos cafés você consumiu nas últimas 24 horas?,"Qual é a temperatura ideal, em °C, para beber café filtrado?",Qual dessas frutas você prefere para suco natural?,Como você classificaria o nível de doçura ideal de um iogurte?,"Quantas refeições você faz por dia, em média?","Qual foi o peso, em gramas, da última porção de arroz que você consumiu?",Qual tipo de dieta você segue atualmente?,Como você avalia sua preferência por alimentos crocantes?,"Quanto tempo, em minutos, você normalmente leva para preparar o café da manhã?"
19,0,50º,Laranja,Médio,4,250,Onívora,4,10
20,2,50,Laranja,Médio,3,300,Onívora,4,2
21,0,35,Laranja,Médio,3,50,Onívora,4,10
22,nenhum,65,Maracujá,Baixo,3,80g,Onívora,1,20 minutos
23,1,65,Laranja,Médio,3,200,Onívora,5,5

In [18]:
print("Quantidade de valores ausentes por coluna:")
print(df.isna().sum())

Quantidade de valores ausentes por coluna:
Quantos cafés você consumiu nas últimas 24 horas?                                 0
Qual é a temperatura ideal, em °C, para beber café filtrado?                      0
Qual dessas frutas você prefere para suco natural?                                0
Como você classificaria o nível de doçura ideal de um iogurte?                    0
Quantas refeições você faz por dia, em média?                                     0
Qual foi o peso, em gramas, da última porção de arroz que você consumiu?          0
Qual tipo de dieta você segue atualmente?                                         0
Como você avalia sua preferência por alimentos crocantes?                         0
Quanto tempo, em minutos, você normalmente leva para preparar o café da manhã?    0
dtype: int64

In [19]:
print("Percentual de valores ausentes por coluna:")
print((df.isna().mean() * 100).round(2))

Percentual de valores ausentes por coluna:
Quantos cafés você consumiu nas últimas 24 horas?                                 0.0
Qual é a temperatura ideal, em °C, para beber café filtrado?                      0.0
Qual dessas frutas você prefere para suco natural?                                0.0
Como você classificaria o nível de doçura ideal de um iogurte?                    0.0
Quantas refeições você faz por dia, em média?                                     0.0
Qual foi o peso, em gramas, da última porção de arroz que você consumiu?          0.0
Qual tipo de dieta você segue atualmente?                                         0.0
Como você avalia sua preferência por alimentos crocantes?                         0.0
Quanto tempo, em minutos, você normalmente leva para preparar o café da manhã?    0.0
dtype: float64

In [20]:
print("Resumo estatístico das variáveis numéricas:")
display(df.describe())

Resumo estatístico das variáveis numéricas:

       Como você avalia sua preferência por alimentos crocantes?
count                                          24.000000
mean                                            3.958333
std                                             1.334465
min                                             1.000000
25%                                             3.750000
50%                                             4.000000
75%                                             5.000000
max                                             5.000000